# [build]
#   command = "npm run build"
#   publish = "build"

[build]
  publish = "public"
  command = "npm run build" # Your build command

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-git-gateway"

